Tue Jul 25 00:30:16 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro P6000                    Off| 00000000:37:00.0 Off |                  Off |
| 26%   17C    P8                8W / 250W|      0MiB / 24576MiB |      0%   E. Process |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
13:4: not a valid test operator: (
13:4: not a valid test operator: 530.30.02
/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py:124: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 805: MPS client failed to connect to the MPS control daemon or the MPS server (Triggered internally at /opt/pytorch/pytorch/c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Training loss :       0.6   Training accuracy :      48717/60000     81.19 %
Validation loss :    0.17   Validation accuracy :     9473/10000     94.73 %
Training loss :      0.21   Training accuracy :      56193/60000     93.65 %
Validation loss :     0.1   Validation accuracy :     9669/10000     96.69 %
Training loss :      0.16   Training accuracy :      57081/60000     95.14 %
Validation loss :   0.087   Validation accuracy :     9724/10000     97.24 %
Training loss :      0.14   Training accuracy :      57508/60000     95.85 %
Validation loss :   0.062   Validation accuracy :     9789/10000     97.89 %
Training loss :      0.12   Training accuracy :      57808/60000     96.35 %
Validation loss :   0.056   Validation accuracy :     9811/10000     98.11 %
Training loss :      0.11   Training accuracy :      58018/60000      96.7 %
Validation loss :   0.051   Validation accuracy :     9829/10000     98.29 %
Training loss :     0.099   Training accuracy :      58190/60000     96.98 %
Validation loss :   0.046   Validation accuracy :     9837/10000     98.37 %
Training loss :     0.093   Training accuracy :      58326/60000     97.21 %
Validation loss :   0.046   Validation accuracy :     9844/10000     98.44 %
Training loss :     0.088   Training accuracy :      58424/60000     97.37 %
Validation loss :   0.042   Validation accuracy :     9864/10000     98.64 %
